name: Deploy to prod server
on: push
jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        echo 'Start Set up SSH'
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 194.32.248.28 >> ~/.ssh/known_hosts 
        echo 'end Set up SSH'

    - name: add new test file
      run: |
        echo 'load changes to prod server'
        ssh -o StrictHostKeyChecking=no root@194.32.248.28 << 'EOF'
        cd stores_dwh_dbt/
        git pull
        echo 'loading is successful'
        echo 'restart dbt docs'
        source venv/bin/activate
        cd stores_dbt
        dbt docs generate
        echo 'restart dbt docs demon'
        sudo systemctl restart dbt_serve.service
        echo 'docs is available on http://194.32.248.28:8081'
        EOF
