name: Test Flow
on: push
jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts 

    - name: add new test file
      run: |
        ssh user@your.server.ip 
        cd /root/stores_dwh_dbt
        git pull
