name: Test Flow
on: workflow_dispatch
jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH
      run: |
        echo 'Start Set up SSH'
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 194.32.248.28 >> ~/.ssh/known_hosts 
        echo 'end Set up SSH'

    - name: add new test file
      run: |
        echo 'start add new test file'
        ssh -o StrictHostKeyChecking=no root@194.32.248.28
        pwd
        git pull
        echo 'end add new test file'
